package cn.edu.techgroup.outsourcing.modules.category.service.impl;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import cn.edu.techgroup.outsourcing.common.error.*; import cn.edu.techgroup.outsourcing.modules.audit.service.AuditRecorder; import cn.edu.techgroup.outsourcing.modules.category.dto.*; import cn.edu.techgroup.outsourcing.modules.category.entity.CategoryEntity; import cn.edu.techgroup.outsourcing.modules.category.mapper.CategoryMapper; import cn.edu.techgroup.outsourcing.modules.user.enums.UserRole; import cn.edu.techgroup.outsourcing.security.LoginUser; import java.time.Instant; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class AdminCategoryServiceImplTest {
 @Mock CategoryMapper mapper; @Mock AuditRecorder audit; AdminCategoryServiceImpl service;
 @BeforeEach void setUp(){service=new AdminCategoryServiceImpl(mapper,audit);}
 @Test void createWritesAudit(){when(mapper.insert(any(CategoryEntity.class))).thenAnswer(i->{CategoryEntity e=i.getArgument(0);e.setId(1L);return 1;});var result=service.create(new CreateAdminCategoryCommand("AI开发",10,"新增常用技术分类"),user(UserRole.ADMIN));assertEquals("1",result.id());verify(audit).record(any(),eq("CATEGORY_CREATE"),eq("CATEGORY"),eq("1"),isNull(),any());}
 @Test void staleUpdateConflicts(){CategoryEntity e=entity();when(mapper.selectByIdForUpdate(1L)).thenReturn(e);BusinessException x=assertThrows(BusinessException.class,()->service.update(1L,new UpdateAdminCategoryCommand(e.getUpdatedAt().minusSeconds(1),"新名称",1,"调整分类展示名称"),user(UserRole.ADMIN)));assertSame(ErrorCode.DATA_VERSION_CONFLICT,x.getErrorCode());verify(mapper,never()).updateById(any(CategoryEntity.class));}
 @Test void expectedTimeIsComparedAtDatabaseMillisecondPrecision(){CategoryEntity e=entity();e.setUpdatedAt(Instant.parse("2026-08-14T10:00:00.123Z"));when(mapper.selectByIdForUpdate(1L)).thenReturn(e);when(mapper.updateById(any(CategoryEntity.class))).thenReturn(1);var out=service.update(1L,new UpdateAdminCategoryCommand(Instant.parse("2026-08-14T10:00:00.123456Z"),"新名称",2,"调整分类展示名称"),user(UserRole.ADMIN));assertEquals(0,out.updatedAt().getNano()%1_000_000);}
 @Test void memberRejectedBeforeDatabase(){assertThrows(BusinessException.class,()->service.create(new CreateAdminCategoryCommand("分类",1,"普通成员尝试新增"),user(UserRole.MEMBER)));verifyNoInteractions(mapper);}
 private CategoryEntity entity(){CategoryEntity e=new CategoryEntity();e.setId(1L);e.setName("原分类");e.setSortOrder(1);e.setEnabled(true);e.setUpdatedAt(Instant.parse("2026-08-14T10:00:00Z"));return e;} private LoginUser user(UserRole r){return new LoginUser(9L,"admin","x","管理员",r,true,true);}
}
